### ISSUE TITLE
Can not build with Tizen Studio 3.2 

### ISSUE THREAD

**Issue by casic** [SamsungDForum/NativePlayer#1]
I have try to test Native Player , but when i build 
error 
pnacl-clang++: pthread: Unable to open file
make: *** [NativePlayer.pexe] Error 255

==================================
python /Users/kostadinzlatev/pepper_42/tools/oshelpers.py rm  NativePlayer_i686.nexe NativePlayer_x86-64.nexe NativePlayer_armv7.nexe  NativePlayer.pexe  ./src/player/url_player/url_player_controller.po  ./src/player/es_dash_player/async_data_provider.po ./src/player/es_dash_player/drm_play_ready.po ./src/player/es_dash_player/es_dash_player_controller.po ./src/player/es_dash_player/packets_manager.po ./src/player/es_dash_player/stream_listener.po ./src/player/es_dash_player/stream_manager.po  ./src/player/player_listeners.po ./src/player/player_provider.po  ./src/demuxer/elementary_stream_packet.po ./src/demuxer/ffmpeg_demuxer.po  ./src/dash/dash_manifest.po ./src/dash/media_segment_sequence.po ./src/dash/representation_builder.po ./src/dash/segment_base_sequence.po ./src/dash/segment_list_sequence.po ./src/dash/segment_template_sequence.po ./src/dash/sequence_iterator.po ./src/dash/util.po  ./src/communicator/message_receiver.po ./src/communicator/message_sender.po  ./src/common.po ./src/logger.po ./src/native_player.po  NativePlayer.nmf
rm: no such file or directory: NativePlayer_i686.nexe
 

16:13:43 Build Finished (took 300ms)

16:13:43 **** Incremental Build of configuration Debug for project NativePlayer ****
make all 
Invoking: NaCl C++ linker
pnacl-clang++ -o "NativePlayer.pexe"  ./src/player/url_player/url_player_controller.po  ./src/player/es_dash_player/async_data_provider.po ./src/player/es_dash_player/drm_play_ready.po ./src/player/es_dash_player/es_dash_player_controller.po ./src/player/es_dash_player/packets_manager.po ./src/player/es_dash_player/stream_listener.po ./src/player/es_dash_player/stream_manager.po  ./src/player/player_listeners.po ./src/player/player_provider.po  ./src/demuxer/elementary_stream_packet.po ./src/demuxer/ffmpeg_demuxer.po  ./src/dash/dash_manifest.po ./src/dash/media_segment_sequence.po ./src/dash/representation_builder.po ./src/dash/segment_base_sequence.po ./src/dash/segment_list_sequence.po ./src/dash/segment_template_sequence.po ./src/dash/sequence_iterator.po ./src/dash/util.po  ./src/communicator/message_receiver.po ./src/communicator/message_sender.po  ./src/common.po ./src/logger.po ./src/native_player.po  -L"/Users/kostadinzlatev/pepper_42/lib/pnacl/Debug" -L"/Users/kostadinzlatev/Downloads/NativePlayer-native_player_42/third_party/lib" -lppapi_cpp -lppapi -lpthread pthread avformat avcodec bz2 avutil m dash curl c++ ssl crypto xml2 z nacl_player nacl_io ppapi ppapi_cpp
pnacl-clang++: pthread: Unable to open file
make: *** [NativePlayer.pexe] Error 255

16:13:44 Build Finished (took 939ms)

**Comment by GrandTeaBrewer** [comment]
Hello, thanks for reporting this issue. It's fixed in 25d1bf4 - builds should work with this commit :).

**Comment by dronja** [comment]
Now i got error:
pnacl-clang++ -o "NativePlayer.pexe"  ./src/player/url_player/url_player_controller.po  ./src/player/es_dash_player/async_data_provider.po ./src/player/es_dash_player/drm_play_ready.po ./src/player/es_dash_player/es_dash_player_controller.po ./src/player/es_dash_player/packets_manager.po ./src/player/es_dash_player/stream_listener.po ./src/player/es_dash_player/stream_manager.po  ./src/player/player_listeners.po ./src/player/player_provider.po  ./src/demuxer/elementary_stream_packet.po ./src/demuxer/ffmpeg_demuxer.po  ./src/dash/dash_manifest.po ./src/dash/media_segment_sequence.po ./src/dash/representation_builder.po ./src/dash/segment_base_sequence.po ./src/dash/segment_list_sequence.po ./src/dash/segment_template_sequence.po ./src/dash/sequence_iterator.po ./src/dash/util.po  ./src/communicator/message_receiver.po ./src/communicator/message_sender.po  ./src/common.po ./src/logger.po ./src/native_player.po  -L"/data/Tizen/NaclSDK/pepper_42/lib/pnacl/Debug" -L"/data/Tizen/PlayerGit/NativePlayer/third_party/lib" -lpthread -lavformat -lavcodec -lbz2 -lavutil -lm -ldash -lcurl -lglibc-compat -lc++ -lssl -lcrypto -lxml2 -lz -lnacl_player -lnacl_io -lppapi -lppapi_cpp
le32-nacl-ld.gold: /mnt/data/b/build/slave/nacl-toolchain/build/native_client/toolchain_build/src/llvm/lib/IR/Metadata.cpp:309: llvm::Value *llvm::MDNode::getOperand(unsigned int) const: Assertion `i < getNumOperands() && "Invalid operand number"' failed.
make: *** [NativePlayer.pexe] Error 250

**Comment by casic** [comment]
So Am I


pnacl-clang++ -o "NativePlayer.pexe"
./src/player/url_player/url_player_controller.po
./src/player/es_dash_player/async_data_provider.po
./src/player/es_dash_player/drm_play_ready.po
./src/player/es_dash_player/es_dash_player_controller.po
./src/player/es_dash_player/packets_manager.po
./src/player/es_dash_player/stream_listener.po
./src/player/es_dash_player/stream_manager.po  ./src/player/player_listeners.po
./src/player/player_provider.po  ./src/demuxer/elementary_stream_packet.po
./src/demuxer/ffmpeg_demuxer.po  ./src/dash/dash_manifest.po
./src/dash/media_segment_sequence.po ./src/dash/representation_builder.po
./src/dash/segment_base_sequence.po ./src/dash/segment_list_sequence.po
./src/dash/segment_template_sequence.po ./src/dash/sequence_iterator.po
./src/dash/util.po  ./src/communicator/message_receiver.po
./src/communicator/message_sender.po  ./src/common.po ./src/logger.po
./src/native_player.po  -L"/Users/kostadinzlatev/pepper_42/lib/pnacl/Debug"
-L"/Users/kostadinzlatev/Downloads/NativePlayer-master/third_party/lib"
-lpthread -lavformat -lavcodec -lbz2 -lavutil -lm -ldash -lcurl
-lglibc-compat -lc++ -lssl -lcrypto -lxml2 -lz -lnacl_player -lnacl_io
-lppapi -lppapi_cpp

Assertion failed: (i < getNumOperands() && "Invalid operand number"),
function getOperand, file
/Volumes/data/b/build/slave/nacl-toolchain/build/native_client/toolchain_build/src/llvm/lib/IR/Metadata.cpp,
line 309.

make: *** [NativePlayer.pexe] Error 250

На ср, 24.04.2019 г. в 11:14 ч. dronja <notifications@github.com> написа:

**Comment by GrandTeaBrewer** [comment]
Reposting from [the other issue](https://github.com/SamsungDForum/NativePlayer/issues/2#issuecomment-486209638) to have things in one place:

> Hi, we keep precompiled third party libraries committed in third_party/*, which allows to download and build NativePlayer without the need to manually build dependencies from webports. The catch is, however, NativePlayer is guaranteed to build out-of-the-box only with the toolchain version that matches precompiled libs.
> 
> Currently, master branch contains libraries for pepper_47, they can indeed fail to compile with pepper_42.

Please try using either newer SDK (preferably 47) or use precompiled libs for SDK v42, which can be found in branch `native_player_42`.

**Comment by casic** [comment]
Finally  I have success . Thanks.  I have compiled , but not work in browser.  I will test on TV / Tizen/

**Comment by MustajabJafry** [comment]
@casic Can you share the demo working project with me, I am trying to build the master repo with pepper_46 but it does not work.
I receive the following error:

```
13:29:30 **** Build of configuration Debug for project NativePlayer ****
make all 
Building file: ../src/player/url_player/url_player_controller.cc
Invoking: NaCl C++ compiler
pnacl-clang++ -I"/include" -I"E:\NativePlayer\src" -I"E:\NativePlayer\third_party\include" -I"E:\NativePlayer\inc" -c -c -std=gnu++0x -g -o "src/player/url_player/url_player_controller.po" "../src/player/url_player/url_player_controller.cc"
/bin/sh: pnacl-clang++: command not found
make: *** [src/player/url_player/subdir.mk:17: src/player/url_player/url_player_controller.po] Error 127

13:29:30 Build Finished (took 273ms)
```
