### ISSUE TITLE
Hello, thanks for reporting this issue. It's fixed in 25d1bf4 - builds should work with this commit :).

### ISSUE THREAD

**Issue by dronja** [SamsungDForum/NativePlayer#2]
Hello, thanks for reporting this issue. It's fixed in 25d1bf4 - builds should work with this commit :).

_Originally posted by @GrandTeaBrewer in https://github.com/SamsungDForum/NativePlayer/issues/1#issuecomment-486109852_

**Comment by dronja** [comment]
When I try to build it, got an error:
pnacl-clang++ -o "NativePlayer.pexe"  ./src/player/url_player/url_player_controller.po  ./src/player/es_dash_player/async_data_provider.po ./src/player/es_dash_player/drm_play_ready.po ./src/player/es_dash_player/es_dash_player_controller.po ./src/player/es_dash_player/packets_manager.po ./src/player/es_dash_player/stream_listener.po ./src/player/es_dash_player/stream_manager.po  ./src/player/player_listeners.po ./src/player/player_provider.po  ./src/demuxer/elementary_stream_packet.po ./src/demuxer/ffmpeg_demuxer.po  ./src/dash/dash_manifest.po ./src/dash/media_segment_sequence.po ./src/dash/representation_builder.po ./src/dash/segment_base_sequence.po ./src/dash/segment_list_sequence.po ./src/dash/segment_template_sequence.po ./src/dash/sequence_iterator.po ./src/dash/util.po  ./src/communicator/message_receiver.po ./src/communicator/message_sender.po  ./src/common.po ./src/logger.po ./src/native_player.po  -L"/data/Tizen/NaclSDK/pepper_42/lib/pnacl/Debug" -L"/data/Tizen/PlayerGit/NativePlayer/third_party/lib" -lpthread -lavformat -lavcodec -lbz2 -lavutil -lm -ldash -lcurl -lglibc-compat -lc++ -lssl -lcrypto -lxml2 -lz -lnacl_player -lnacl_io -lppapi -lppapi_cpp
le32-nacl-ld.gold: /mnt/data/b/build/slave/nacl-toolchain/build/native_client/toolchain_build/src/llvm/lib/IR/Metadata.cpp:309: llvm::Value *llvm::MDNode::getOperand(unsigned int) const: Assertion `i < getNumOperands() && "Invalid operand number"' failed.
make: *** [NativePlayer.pexe] Error 250

Problem was in pepper_42.

**Comment by GrandTeaBrewer** [comment]
Hi, we keep precompiled third party libraries committed in `third_party/*`, which allows to download and build NativePlayer without the need to manually build dependencies from [webports](https://github.com/SamsungDForum/Webports). The catch is, however, NativePlayer is guaranteed to build out-of-the-box only with the toolchain version that matches precompiled libs.

Currently, master branch contains libraries for pepper_47, they can indeed fail to compile with pepper_42.
