### ISSUE TITLE
RTP stream

### ISSUE THREAD

**Issue by dronja** [SamsungDForum/NativePlayer#3]
Is there an example how to use the player to play rtp stream?

**Comment by abujalski** [comment]
Please check: https://github.com/PhysicalGraph/STAVPlay

**Comment by dronja** [comment]
Thanks, @abujalski, thank you a lot!

**Comment by rockinggit** [comment]
I tried given example for rtsp stream for 2019 TV. It does not work.
any working URL for ex. rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov

fails at avformat_open_input(&format_ctx, url.c_str(),NULL, NULL);

I think enable network is disabled in ffmpeg compiled lib in this sample. so URL passing is not working.
however rtsp options are being set but it seems not to be working.
av_dict_set(&opts, "rtsp_transport", "tcp", 0);
 avformat_open_input(&format_ctx, url.c_str(),NULL, opts);
Can anyone confirm on which year tv model this sample is working?

**Comment by dronja** [comment]
Hi, @rockinggit! I've tested this player on 2018 TV models, and it works pretty fine. But a minimum latency, that I've recieved was about 2s. I think some latency gives rtsp server.

**Comment by rockinggit** [comment]
Hi @dronja ! did you used ffmpeg version given in sample or compiled yourself for tizen. I am always getting failure in avformat_open_input with "protocol not found" error.
Did you changed anything in project to get it work ? i can't get it why it is not working for me.

**Comment by dronja** [comment]
@rockinggit , I've used ffmpeg version given in sample and changed nothing. Check with Wireshark your rtp packets.

**Comment by rockinggit** [comment]
Hi @dronja, How did you imported this sample to Tizen Studio ? Can you please let me know Studio version which you are using ? Nacl Toolchain version ? and a few steps which you follow to import and build ?

When i try to import this project in Tizen Studio it comes as tv-samsung-public 2.4 project. (did you change configuration of this project to build ?)
I dont see any Build option same as Nacl Projects. I can only do "Build Signed Package" and Run As ->"Tizen Web Application" which actually does nothing as no Nacl file is being generated. (.pexe, .nexe etc.)

**Comment by dronja** [comment]
I've answered [here](https://github.com/PhysicalGraph/STAVPlay/issues/11)
