### ISSUE TITLE
Live HLS   playlist  duration problem

### ISSUE THREAD

**Issue by casic** [SamsungDForum/NativePlayer#7]
I'm working on  app for TV streams player. 
I have made  Tizen WebApp   with AV_player  but there is a problem with duration of  HLS live /NOT VOD/. 
So i decide to use native player. But native player do so -  2 hour . play list return   17s . duration ....
How can i make timeshift  -   STOP, REWIND   in live stream ??????
Please help. 
I use this in android and  webOS , and NO SUCH PROBLEMS.  

And getCurrentTime() return    7196 s , ie.  in the end of 7200 seconds playlist. This is right.  But getMediaDuration() return   -  17   !!!????

**Comment by abujalski** [comment]
Hi,
When you use NaCl Player to play content from given URL it uses the same backend (playlist parsing, content download logic, etc) as AVPlay, so this suggests error in the backend.

Can you share:
- link to the playlist?
- information which TV model year ('17, '18) are you working on?

**Comment by casic** [comment]
Hi , thanks for your response.  I have understand already that the error is in  low level and the player is the same.  In fact  i always receive  value  - 0 /zero/   getDuration()

function handleNaclMessage(message_event) {
  var message = message_event.data;
  
  console.log (message);
  if (printIfLog(message)) {  // function defined in common.js
    return;   // this was a log or error message, so we can finish this handling
  }

  if (!message_event.data.messageFromPlayer)
    return;

  switch (message_event.data.messageFromPlayer) {
  case MessageFromPlayerEnum.kTimeUpdate:
    updateCurrentTime( message_event.data.time)
    break;
  case MessageFromPlayerEnum.kSetDuration:
    clip_duration = message_event.data.time;
    console.log (message_event.data);
    clip_duration = parseFloat(clip_duration);
    document.getElementById('total_time').innerHTML = clip_duration;
    break;

I'm   test on  2018 TV  ,  also .  Emulator -  same things.  
When i play   HLS  /m3u8/  with parameter VoD  there is no problem.

But when i'm playing   HLS  with  720    10 seconds   chunks ,  duration  is 0.  
I'm playing this  HLS streams  with  ExoPlayer,  and  HTML player in WebOS , there is no problem and i can rewind forward , stop, play    live HLS stream .
Give me email to send you  stream  link .
Best regards 
Thanks in advance .

**Comment by abujalski** [comment]
Please send this stream to a.bujalski@samsung.com .

Thanks.

**Comment by casic** [comment]
Maybe this is the same issue ????

https://www.oipapio.com/question-3017622

https://github.com/SamsungInternet/support/issues/5

**Comment by abujalski** [comment]
Closing this issue as related to streaming engine on Samsung Smart TV and is not related to native_player application itself.

For further support please report Q&A as described in [Samsung Apps TV Seller Office](https://developer.samsung.com/tv/distribute/seller-office/).
